import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "@/app/_styles/globals.css";
import Header from "@/app/_components/Header";

const franklinGothic = localFont({
  src: [
    {
      path: "../public/fonts/FranklinGothic_Demi.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-franklin",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Welcome to Elevet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${franklinGothic.variable} ${inter.className} antialiased bg-[url(/img/bg.png)] min-h-screen bg-cover bg-center bg-no-repeat text-white`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
